### ISSUE TITLE
m1编译失败

### ISSUE THREAD

**Issue by hudangwei** [ant4g0nist/crashwrangler#1]
编译报错了，错误信息是：
xcrun --sdk macosx cc -arch arm64 -g -lcapstone -L/usr/local/lib -I/usr/local/include -F/System/Library/PrivateFrameworks -framework CoreSymbolication -framework IOKit -framework Foundation -framework ApplicationServices -framework Symbolication -framework CoreServices -framework CrashReporterSupport -framework CoreFoundation -framework CommerceKit -o exc_handler exc_handler.o arm64_disasm.o -framework CrashReporterSupport mach_excUser.o mach_excServer.o
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CrashReport", referenced from:
      objc-class-ref in exc_handler.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [exc_handler_silicon] Error 1

请问大佬，该如何修复呢？

**Comment by ant4g0nist** [comment]
Please find detailed thread here: https://twitter.com/ant4g0nist/status/1692797923354939792?s=20
