### ISSUE TITLE
Ventura support please

### ISSUE THREAD

**Issue by awakened1712** [ant4g0nist/crashwrangler#2]
It seems `[CrashReport initWithTask:task exceptionType:exceptionCode:exceptionCodeCount:thread:threadStateFlavor:threadState:threadStateCount: in_state_count]` does not exist any more. Any hints please?

**Comment by ant4g0nist** [comment]
Hey! 

Currently I'm occupied to support this. I have another project "crashmon - A CrashWrangler replacement based on LLDB". Can you please give [crashmon](https://github.com/ant4g0nist/crashmon) a try?

Thank you 🙏

**Comment by ant4g0nist** [comment]
Hey @awakened1712 please checkout this thread! https://twitter.com/ant4g0nist/status/1692797923354939792?s=20
